### PR TITLE
Heap allocation exercise from Chapter 13

### PR DESCRIPTION
**Pull request by allancalix**
Easy waste memory on your machine!

```sh
cargo run --bin heap-allocator 400 // consumes 400 mebibytes
```

### CODE REVIEW

**Comment by allancalix** [comment]
@jafow Random contribution to the cause!

**Review by jafow — APPROVED** [review]
Cool!

**Comment by allancalix** [comment]
I can't merge this!

**Comment by jafow** [comment]
Oops I'll bump your perms

**Pull request merged**
